//! Catálogos pequenos para completion local quando não há LSP disponível.

use oride_syntax::LanguageId;

pub(crate) fn completion_words(language: LanguageId) -> &'static [&'static str] {
    match language {
        LanguageId::OriScript => ORISCRIPT_WORDS,
        LanguageId::Ori => ORI_WORDS,
        LanguageId::Rust => RUST_WORDS,
        LanguageId::C => C_WORDS,
        LanguageId::Bash => BASH_WORDS,
        LanguageId::Python => PYTHON_WORDS,
        LanguageId::JavaScript | LanguageId::TypeScript | LanguageId::Tsx => WEB_WORDS,
        LanguageId::Ruby => RUBY_WORDS,
        LanguageId::Nim => NIM_WORDS,
        LanguageId::D => D_WORDS,
        LanguageId::Lua => LUA_WORDS,
        LanguageId::Html => HTML_WORDS,
        LanguageId::Css => CSS_WORDS,
        LanguageId::Plain | LanguageId::Markdown | LanguageId::Mdx | LanguageId::Custom(_) => &[],
    }
}

const ORISCRIPT_WORDS: &[&str] = &[
    "async", "await", "break", "const", "continue", "else", "enum", "false", "fn", "for", "if",
    "import", "in", "let", "match", "module", "null", "return", "struct", "true", "type", "while",
];

const ORI_WORDS: &[&str] = &[
    "alias", "and", "any", "apply", "as", "attr", "bool", "break", "bytes", "case", "check",
    "const", "continue", "elif", "else", "end", "enum", "extern", "false", "float", "for",
    "handle", "if", "import", "imports", "in", "int", "is", "lazy", "list", "loop", "map", "match",
    "module", "mut", "newtype", "none", "not", "optional", "or", "public", "range", "repeat",
    "result", "return", "self", "set", "some", "string", "struct", "then", "trait", "true",
    "tuple", "use", "using", "var", "void", "where", "while", "with",
];

const RUST_WORDS: &[&str] = &[
    "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "Self", "static", "struct", "trait", "true", "type", "unsafe", "use",
    "where", "while",
];

const PYTHON_WORDS: &[&str] = &[
    "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del", "elif",
    "else", "except", "False", "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "None", "nonlocal", "not", "or", "pass", "raise", "return", "True", "try", "while",
    "with", "yield",
];

const WEB_WORDS: &[&str] = &[
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "from",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "keyof",
    "let",
    "new",
    "null",
    "private",
    "protected",
    "public",
    "readonly",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "var",
    "void",
    "while",
    "yield",
];

const RUBY_WORDS: &[&str] = &[
    "alias", "and", "begin", "break", "case", "class", "def", "defined?", "do", "else", "elsif",
    "end", "ensure", "false", "for", "if", "in", "module", "next", "nil", "not", "or", "redo",
    "rescue", "retry", "return", "self", "super", "then", "true", "undef", "unless", "until",
    "when", "while", "yield",
];

const NIM_WORDS: &[&str] = &[
    "and", "as", "block", "break", "case", "const", "continue", "defer", "discard", "distinct",
    "elif", "else", "enum", "except", "export", "finally", "for", "from", "func", "if", "import",
    "in", "include", "iterator", "let", "macro", "method", "nil", "not", "object", "of", "or",
    "proc", "raise", "ref", "return", "template", "try", "tuple", "type", "var", "when", "while",
    "yield",
];

const HTML_WORDS: &[&str] = &[
    "article", "aside", "body", "button", "div", "footer", "form", "head", "header", "html", "img",
    "input", "label", "li", "link", "main", "meta", "nav", "ol", "option", "script", "section",
    "select", "span", "style", "table", "textarea", "title", "ul",
];

const CSS_WORDS: &[&str] = &[
    "align-items",
    "background",
    "border",
    "color",
    "display",
    "flex",
    "font-family",
    "font-size",
    "gap",
    "grid",
    "height",
    "justify-content",
    "margin",
    "max-width",
    "min-width",
    "overflow",
    "padding",
    "position",
    "transform",
    "transition",
    "width",
    "z-index",
];

const D_WORDS: &[&str] = &[
    "abstract",
    "alias",
    "align",
    "asm",
    "assert",
    "auto",
    "body",
    "bool",
    "break",
    "byte",
    "case",
    "cast",
    "catch",
    "cdouble",
    "cent",
    "cfloat",
    "char",
    "class",
    "const",
    "continue",
    "creal",
    "dchar",
    "debug",
    "default",
    "delegate",
    "delete",
    "deprecated",
    "do",
    "double",
    "else",
    "enum",
    "export",
    "extern",
    "false",
    "final",
    "finally",
    "float",
    "for",
    "foreach",
    "foreach_reverse",
    "function",
    "goto",
    "idouble",
    "if",
    "ifloat",
    "immutable",
    "import",
    "in",
    "inout",
    "int",
    "interface",
    "invariant",
    "ireal",
    "is",
    "lazy",
    "long",
    "macro",
    "mixin",
    "module",
    "new",
    "nothrow",
    "null",
    "out",
    "override",
    "package",
    "pragma",
    "private",
    "protected",
    "public",
    "pure",
    "real",
    "ref",
    "return",
    "scope",
    "shared",
    "short",
    "size_t",
    "static",
    "string",
    "struct",
    "super",
    "switch",
    "synchronized",
    "template",
    "this",
    "throw",
    "true",
    "try",
    "typeid",
    "typeof",
    "ubyte",
    "ucent",
    "uint",
    "ulong",
    "union",
    "unittest",
    "ushort",
    "version",
    "void",
    "wchar",
    "while",
    "with",
];

const C_WORDS: &[&str] = &[
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else",
    "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long", "register",
    "restrict", "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef",
    "union", "unsigned", "void", "volatile", "while", "NULL", "size_t", "uint8_t", "uint16_t",
    "uint32_t", "uint64_t", "int8_t", "int16_t", "int32_t", "int64_t", "bool", "true", "false",
];

const BASH_WORDS: &[&str] = &[
    "alias", "bg", "bind", "break", "builtin", "case", "cd", "command", "compgen", "complete",
    "continue", "declare", "dirs", "disown", "do", "done", "echo", "elif", "else", "enable",
    "esac", "eval", "exec", "exit", "export", "false", "fc", "fg", "fi", "for", "function",
    "getopts", "hash", "help", "history", "if", "in", "jobs", "kill", "let", "local", "logout",
    "popd", "printf", "pushd", "pwd", "read", "readonly", "return", "set", "shift", "shopt",
    "source", "suspend", "test", "then", "time", "times", "trap", "true", "type", "typeset",
    "ulimit", "umask", "unalias", "unset", "until", "wait", "while",
];

const LUA_WORDS: &[&str] = &[
    "and",
    "break",
    "coroutine",
    "do",
    "else",
    "elseif",
    "end",
    "false",
    "for",
    "function",
    "goto",
    "if",
    "in",
    "io",
    "local",
    "math",
    "nil",
    "not",
    "or",
    "os",
    "package",
    "repeat",
    "return",
    "self",
    "string",
    "table",
    "then",
    "true",
    "until",
    "while",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_l1_language_has_offline_words() {
        for language in [
            LanguageId::OriScript,
            LanguageId::Ori,
            LanguageId::Rust,
            LanguageId::C,
            LanguageId::Bash,
            LanguageId::Python,
            LanguageId::JavaScript,
            LanguageId::TypeScript,
            LanguageId::Tsx,
            LanguageId::Ruby,
            LanguageId::Nim,
            LanguageId::D,
            LanguageId::Lua,
        ] {
            assert!(!completion_words(language).is_empty(), "{language:?}");
        }
    }
}
