[package]
name = "oride"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Oride — modular, lightweight terminal code editor and mini-IDE in Rust"
rust-version.workspace = true

[[bin]]
name = "oride"
path = "src/main.rs"

[dependencies]
oride-app = { workspace = true }
oride-core = { workspace = true }
anyhow = { workspace = true }
